// ============================================
// Auto-generated by DialUp SDK Generator
// DO NOT MODIFY - Changes will be overwritten
// ============================================

#pragma once
#include <cstddef>
#include <string>

#include "Object.h"
#include "LayoutTraits.h"

class FNameEntryEntry: public ObjectEntry, LayoutTraits<FNameEntry, FName> {
public:
    using ObjectEntry::ObjectEntry;

    auto getDefaultClassName() const -> std::string override { return "FNameEntry"; }
    auto getCanonicalType() const -> EClassTypes override { return EClassTypes::FName; }
    auto getCanonicalTypeStr() const -> std::string override { return "FNameEntry"; }
    auto getCacheType() const -> std::string override { return "FNameEntry"; }
};