// ============================================
// Auto-generated by DialUp SDK Generator
// DO NOT MODIFY - Changes will be overwritten
// ============================================

#pragma once
#include <cstddef>
#include <string>

#include "Object.h"
#include "LayoutTraits.h"

class UFieldEntry : public ObjectEntry, LayoutTraits<UField, UObject> {
public:
    using ObjectEntry::ObjectEntry;
    auto getCanonicalType() const -> EClassTypes override { return EClassTypes::UField; }
    auto getCanonicalTypeStr() const -> std::string override { return "UField"; }
    auto getCacheType() const -> std::string override { return "UFieldEntry"; }
    auto getDefaultClassName() const -> std::string override { return "UField"; }
};