// ============================================
// Auto-generated by DialUp SDK Generator
// DO NOT MODIFY - Changes will be overwritten
// ============================================

#pragma once
#include <string>

#include "Object.h"
#include "LayoutTraits.h"

class UObjectEntry final : public ObjectEntry, LayoutTraits<UObject, UObject> {
public:
    using ObjectEntry::ObjectEntry;
    std::string getDefaultClassName() const override { return "UObject"; }
    auto getCacheType() const -> std::string override { return "UObjectEntry"; }
};