// ============================================
// Auto-generated by DialUp SDK Generator
// DO NOT MODIFY - Changes will be overwritten
// ============================================

#pragma once

static ptrdiff_t roundUp(const ptrdiff_t val, const ptrdiff_t align) {
    return (val + align - 1) & ~(align - 1);
}