// ============================================
// Auto-generated by DialUp SDK Generator
// DO NOT MODIFY - Changes will be overwritten
// ============================================

#pragma once
#include <string>

#include "Object.h"
#include "Schema.h"

#include "ValueResolver.h"

//
//
//Option 2: Strongly-typed access via templated helpers
//
//If you want compile-time type safety where possible:
//
//template<typename T>
//T& PropertyEntry::getValue(void* params) const {
//    return *reinterpret_cast<T*>(
//        static_cast<uint8_t*>(params) + getOffset()
//    );
//}
//
//Then gate it using canonical type checks:
//
//if (prop->getCanonicalType() == "uint32_t") {
//    uint32_t v = prop->getValue<uint32_t>(params);
//}
//This is ideal for mutation hooks.


// make getCanonicalType getCanonicalTypeStr
// then have it return the enum
// access like:
//
// void PropertyEntry::setValue(void* params, const Variant& val) {
//     void* v = getValuePtr(params);
//
//     switch (getCanonicalType()) {
//         case CanonicalType::Int32:
//             *reinterpret_cast<int32_t*>(v) = val.as<int32_t>();
//             break;
//
//         case CanonicalType::Bool:
//             setBool(v, val.as<bool>());
//             break;
//
//             // etc
//     }
// }


class PropertyEntry : public ObjectEntry {
public:
    using ObjectEntry::ObjectEntry;

protected:
    template<typename Resolver>
    void resolveVia(ResolvedValue& out, void* valuePtr) const {
        static_cast<const Resolver*>(this)->Resolver::resolveInto(out, valuePtr);
    }

public:

    auto getValuePtr(void *params) const -> void * {
        return static_cast<uint8_t*>(params) + getOffset();
    }

    virtual auto getResolvedKind() const -> ResolvedValue::Kind = 0;
    virtual auto getStorageType() const -> ResolvedValue::StorageType = 0;
    // fixme need to implement on others
    //virtual void resolveInto(ResolvedValue& out, void* valuePtr) const = 0;
    virtual void resolveInto(ResolvedValue& out, void* valuePtr) const {}

    auto resolveValue(void* params) const -> ResolvedValue {
        ResolvedValue v;
        v.kind = getResolvedKind();
        // fixme move these to class and outside of the resolvers for reuse with SDK
        v.data = getValuePtr(params);
        v.storage = getStorageType();

        resolveInto(v, v.data);
        return v;
    }

//    auto toString(void *params) const -> std::string {
//        void* v = getValuePtr(params);
//
//        switch (getCanonicalType()) {
//            case EClassTypes::Bool:
//                return getBool(v) ? "true" : "false";
//
//            case EClassTypes::Int32:
//                return std::to_string(*reinterpret_cast<int32_t*>(v));
//
//            case EClassTypes::UInt32:
//                return std::to_string(*reinterpret_cast<uint32_t*>(v));
//
//            case EClassTypes::Float:
//                return std::to_string(*reinterpret_cast<float*>(v));
//
//            case EClassTypes::UObjectPtr: {
//                auto* obj = *reinterpret_cast<UObject**>(v);
//                return obj ? obj->GetFullName() : "nullptr";
//            }
//
//            case EClassTypes::Struct:
//                return "<struct>";
//
//            case EClassTypes::Array:
//                return "<array>";
//
//            default:
//                return "<unknown>";
//        }
//    }

    auto asProperty() const -> UProperty* { return static_cast<UProperty*>(getObject()); }
    auto asBoolProperty() const -> UBoolProperty* { return static_cast<UBoolProperty*>(getObject()); }

    auto isArray() const -> bool { return getArrayDim() > 1; }

    virtual auto getSize() const -> ptrdiff_t { return asProperty()->ElementSize; }

    auto getBitMask() const -> uint32_t { return asBoolProperty()->BitMask; }
    auto getArrayDim() const -> ptrdiff_t { return asProperty()->ArrayDim; }
    auto getElementSize() const -> ptrdiff_t { return asProperty()->ElementSize; }
    auto getOffset() const -> ptrdiff_t { return asProperty()->Offset; }
    auto getTotalSize() const -> ptrdiff_t { return getArrayDim() * getElementSize(); }
    auto getPropertyFlags() const -> uint64_t {
        if (!flags_) { flags_ = asProperty()->PropertyFlags; }
        return flags_;
    }

    auto isValidProperty() const -> bool {
        if (!getObject()) {
            Logger::instance().log("[WARNING] Invalid property {}: null object", getName());
            return false;
        }

        if (!getObject()->IsA(UProperty::StaticClass())) {
            Logger::instance().log("[WARNING] Invalid property {}: not a UProperty", getName());
            return false;
        }

        if (!getElementSize()) {
            Logger::instance().log("[WARNING] Invalid property {}: zero element size", getName());
            return false;
        }

        if (getType() == EClassTypes::Unknown) {
            Logger::instance().log("[WARNING] Invalid property {}: unknown type - {}", getName(), getObject()->Class->GetName());
            return false;
        }

        //Logger::instance().log("[INFO] Valid property: {} (type: {})", getName(), static_cast<int>(getType()));
        return true;
    }

    // Some real layout-affecting properties can have:
    // ElementSize == 0
    // bitfields
    // bool-packed flags
    // engine-internal padding props
    // They still move offsets forward and therefore define memory, even if they don’t generate fields.
    // So for inheritance eligibility, element size must NOT be a gate.
    auto definesLayoutPast(ptrdiff_t parentSize) const -> bool {
        if (!getObject()) return false;
        if (!getObject()->IsA(UProperty::StaticClass())) return false;

        return getOffset() >= parentSize;
    }

    auto isArgument() const -> bool override { return isValidProperty() && (getPropertyFlags() & CPF_Parm) && !(getPropertyFlags() & CPF_OutParm) && !(getPropertyFlags() & CPF_ReturnParm); }
    auto isOptional() const -> bool override { return isValidProperty() && getPropertyFlags() & CPF_OptionalParm; }
    auto isOutParam() const -> bool override { return isValidProperty() && (getPropertyFlags() & CPF_OutParm) && (getPropertyFlags() & CPF_Parm); }
    auto isReturnParam() const -> bool override { return isValidProperty() && (getPropertyFlags() & CPF_ReturnParm) && (getPropertyFlags() & CPF_Parm); }
    auto isTriviallyCopyable() const -> bool override { return false; }
    virtual auto canConst() const -> bool { return false; }

    // we are at the lowest level, there's no more to iterate
    auto wasIterated() const -> bool override { return true; }

    // dependencies for topo sorting structs
    virtual auto getStructDependencyTypes() const -> const std::unordered_set<std::string>& { return EMPTY_STR_SET; }

    auto getFormattedArgType() const -> std::string {
        std::string baseType = getCanonicalTypeStr();
        // fixme
        if (getCanonicalTypeStr() == "SearchStatusOwner") {
            baseType = "ESearchStatusOwner";
        }
        if (isReturnParam()) { return baseType; }
        if (isOutParam()) { return baseType + "&"; }
        if (canConst()) { return "const " + baseType + "&"; }
        return baseType;
    }

protected:
    mutable std::unordered_set<std::string> dependencyTypes_;

private:
    mutable uint64_t flags_{0};
};