// ============================================
// Auto-generated by DialUp SDK Generator
// DO NOT MODIFY - Changes will be overwritten
// ============================================

#include "Runtime.h"
#include "Schema.h"
#include "SDK.h"

void Runtime::create() {
    if (!instance_) instance_ = new Runtime();
}

auto Runtime::instance() -> Runtime& {
    return *instance_;
}

void Runtime::yeet() {
    delete instance_;
    instance_ = nullptr;
}

auto Runtime::getFNameEntries() const -> TArray<FNameEntry*>& { return *fNameEntries_; }

auto Runtime::getFNameEntry(const int32_t index) -> FNameEntry* {
    if (index < 0 || index >= getFNameEntries().size()) {
        return nullptr;
    }
    return getFNameEntries()[index];
}

auto Runtime::findClass(const std::string& classFullName) -> UClass* {
    return instance().findClassImpl(classFullName);
}

auto Runtime::findClassImpl(const std::string& classFullName) -> UClass* {
    if (classCache_.empty()) {
        for (int32_t i = 0; i < uObjects_->size() - 1; i++) {
            if (UObject* uObject = uObjects_->at(i)) {
                if (std::string objectFullName = uObject->GetFullName(); objectFullName.find("Class") == 0) {
                    classCache_[objectFullName] = reinterpret_cast<UClass*>(uObject);
                }
            }
        }
    }

    if (classCache_.contains(classFullName)) {
        return classCache_[classFullName];
    }

    return nullptr;
}

auto Runtime::findFunction(const std::string& functionFullName) -> UFunction* {
    return instance().findFunctionImpl(functionFullName);
}

auto Runtime::findFunctionImpl(const std::string& functionFullName) -> UFunction* {
    if (functionCache_.empty()) {
        for (int32_t i = 0; i < uObjects_->size() - 1; i++) {
            if (UObject* uObject = uObjects_->at(i)) {
                if (std::string objectFullName = uObject->GetFullName(); objectFullName.find("Function") == 0) {
                    functionCache_[objectFullName] = reinterpret_cast<UFunction*>(uObject);
                }
            }
        }
    }

    if (functionCache_.contains(functionFullName)) {
        return functionCache_[functionFullName];
    }

    return nullptr;
}

auto Runtime::findPackages() -> std::vector<UObject*> {
    static std::vector<UObject*> packages;
    if (packages.empty()) {
        for (int i = 0; i < 10; ++i) {
            if (UObject* obj = getUObjects().at(i); obj && !obj->GetName().empty()) {
                //Logger::log("Found package: " + obj->GetName());
                packages.emplace_back(obj);
            }
        }
    }
    return packages;
}

auto Runtime::getFNameEntryName(const int32_t index) -> std::string {
    const FNameEntry* entry = getFNameEntry(index);
    return entry ? entry->ToString() : "";
}

auto Runtime::areFNameEntriesValid() -> bool {
    if (getFNameEntries().empty()) {
        //ILogger::instance().log("FNames not populated");
        return false;
    }

    if (getFNameEntries().at(0)->ToString() != "None") {
        //ILogger::instance().log("First FName should always be 'None'");
        return false;
    }

    if (getFNameEntries().size() < 1000) {
        //ILogger::instance().log("Game should have more FNames");
        return false;
    }

    return true;
}

auto Runtime::areUObjectsPopulated() const -> bool {
    if (getUObjectsPtr()->empty()) {
        //ILogger::instance().log("UObjects not populated");
        return false;
    }
    return true;
}