// ============================================
// Auto-generated by DialUp SDK Generator
// DO NOT MODIFY - Changes will be overwritten
// ============================================

#pragma once
#include <string>

#include "LayoutTraits.h"
#include "Property.h"
#include "resolve/Boolean.h"

class UBoolPropertyEntry : public PropertyEntry, LayoutTraits<UBoolProperty, UProperty> {
public:
    using PropertyEntry::PropertyEntry;

    void resolveInto(ResolvedValue& out, void* valuePtr) const override {
        BooleanResolver::resolve(out, valuePtr, getBitMask());
    }

    auto getCanonicalTypeStr() const -> std::string override { return "uint32_t"; }
    auto getCacheType() const -> std::string override { return "UBoolPropertyEntry"; }
    auto getDefaultClassName() const -> std::string override { return "UBoolProperty"; }
    bool isTriviallyCopyable() const override { return false; }
    bool canConst() const override { return false; }
};