// ============================================
// Auto-generated by DialUp SDK Generator
// DO NOT MODIFY - Changes will be overwritten
// ============================================

#pragma once
#include <string>

#include "LayoutTraits.h"
#include "Property.h"
#include "resolve/Byte.h"

class UBytePropertyEntry final : public PropertyEntry, LayoutTraits<UByteProperty, UProperty> {
public:
    using PropertyEntry::PropertyEntry;

    void resolveInto(MyResolvedValue& out, void* valuePtr) const override {
        ByteResolver::resolve(out, valuePtr, asByteProperty()->Enum);
    }

    auto asByteProperty() const -> UByteProperty* { return static_cast<UByteProperty*>(getObject()); }
    auto getCanonicalTypeStr() const -> std::string override {
        if (asByteProperty()->Enum) {
            return asByteProperty()->Enum->GetName();
        }
        return "uint8_t";
    }
    auto getCacheType() const -> std::string override { return "UBytePropertyEntry"; }
    auto getDefaultClassName() const -> std::string override { return "UByteProperty"; }
    bool isTriviallyCopyable() const override { return true; }
    bool canConst() const override { return false; }
};