// ============================================
// Auto-generated by DialUp SDK Generator
// DO NOT MODIFY - Changes will be overwritten
// ============================================

#pragma once
#include <string>

#include "LayoutTraits.h"
#include "Property.h"
#include "resolve/Class.h"

class UClassPropertyEntry final : public PropertyEntry, LayoutTraits<UClassProperty, UProperty> {
public:
    using PropertyEntry::PropertyEntry;

    void resolveInto(ResolvedValue& out, void* valuePtr) const override {
        ClassResolver::resolve(out, valuePtr);
    }

    auto getCanonicalTypeStr() const -> std::string override { return "UClass*"; }
    auto getCacheType() const -> std::string override { return "UClassPropertyEntry"; }
    auto getDefaultClassName() const -> std::string override { return "UClassProperty"; }
    bool isTriviallyCopyable() const override { return false; }
    bool canConst() const override { return false; }
    auto getSize() const -> ptrdiff_t override { return sizeof(uintptr_t); }
};
