// ============================================
// Auto-generated by DialUp SDK Generator
// DO NOT MODIFY - Changes will be overwritten
// ============================================

#pragma once
#include <string>

#include "LayoutTraits.h"
#include "Property.h"
#include "resolve/Float.h"

class UFloatPropertyEntry final : public PropertyEntry, LayoutTraits<UFloatProperty, UProperty> {
public:
    using PropertyEntry::PropertyEntry;

    void resolveInto(MyResolvedValue& out, void* valuePtr) const override {
        FloatResolver::resolve(out, valuePtr);
    }

    auto getCanonicalTypeStr() const -> std::string override { return "float"; }
    auto getCacheType() const -> std::string override { return "UFloatPropertyEntry"; }
    auto getDefaultClassName() const -> std::string override { return "UFloatProperty"; }
    bool isTriviallyCopyable() const override { return true; }
    bool canConst() const override { return false; }
    auto getSize() const -> ptrdiff_t override { return sizeof(float); }
};
