// ============================================
// Auto-generated by DialUp SDK Generator
// DO NOT MODIFY - Changes will be overwritten
// ============================================

#pragma once
#include <cstdint>
#include <string>

#include "LayoutTraits.h"
#include "Property.h"
#include "resolve/Integer.h"

class UIntPropertyEntry final : public PropertyEntry, LayoutTraits<UIntProperty, UProperty> {
public:
    using PropertyEntry::PropertyEntry;

    void resolveInto(ResolvedValue& out, void* valuePtr) const override {
        IntegerResolver::resolve(out, valuePtr);
    }

    auto getCanonicalTypeStr() const -> std::string override { return "int32_t"; }
    auto getCacheType() const -> std::string override { return "UIntPropertyEntry"; }
    auto getDefaultClassName() const -> std::string override { return "UIntProperty"; }
    auto isTriviallyCopyable() const -> bool override { return true; }
    auto canConst() const -> bool override { return false; }
    auto getSize() const -> ptrdiff_t override { return sizeof(int32_t); }
};