// ============================================
// Auto-generated by DialUp SDK Generator
// DO NOT MODIFY - Changes will be overwritten
// ============================================

#pragma once
#include <string>

#include "LayoutTraits.h"
#include "Property.h"
#include "resolve/FName.h"

class UNamePropertyEntry final : public PropertyEntry, LayoutTraits<UNameProperty, UProperty> {
public:
    using PropertyEntry::PropertyEntry;

    void resolveInto(MyResolvedValue& out, void* valuePtr) const override {
        FNameResolver::resolve(out, valuePtr);
    }

    auto getCanonicalType() const -> EClassTypes override { return EClassTypes::FName; }
    auto getCanonicalTypeStr() const -> std::string override { return "FName"; }
    auto getCacheType() const -> std::string override { return "UNamePropertyEntry"; }
    auto getDefaultClassName() const -> std::string override { return "UNameProperty"; }
    bool isTriviallyCopyable() const override { return false; }
    bool canConst() const override { return false; }
    auto getSize() const -> ptrdiff_t override { return sizeof(FName); }
};