// ============================================
// Auto-generated by DialUp SDK Generator
// DO NOT MODIFY - Changes will be overwritten
// ============================================

#pragma once
#include <string>

#include "LayoutTraits.h"
#include "Property.h"
#include "resolve/FString.h"

class UStrPropertyEntry final : public PropertyEntry, LayoutTraits<UStrProperty, UProperty> {
public:
    using PropertyEntry::PropertyEntry;

    void resolveInto(MyResolvedValue& out, void* valuePtr) const override {
        IntegerResolver::resolve(out, valuePtr);
    }

    auto getCanonicalTypeStr() const -> std::string override { return "FString"; }
    auto getCacheType() const -> std::string override { return "UStrPropertyEntry"; }
    auto getDefaultClassName() const -> std::string override { return "UStrProperty"; }
    bool isTriviallyCopyable() const override { return false; }
    bool canConst() const override { return false; }
    auto getSize() const -> ptrdiff_t override { return sizeof(FString); }
};